var annotated_dup =
[
    [ "download", "namespacedownload.html", [
      [ "BranchMeta", "classdownload_1_1_branch_meta.html", null ],
      [ "BinMeta", "classdownload_1_1_bin_meta.html", null ]
    ] ],
    [ "energy_tracker", "namespaceenergy__tracker.html", [
      [ "EnergyTracker", "classenergy__tracker_1_1_energy_tracker.html", "classenergy__tracker_1_1_energy_tracker" ]
    ] ],
    [ "evaluator", null, [
      [ "CompressionEvaluator", "classevaluator_1_1_compression_evaluator.html", "classevaluator_1_1_compression_evaluator" ]
    ] ],
    [ "gpu_range_coder", null, [
      [ "_ModelStub", "classgpu__range__coder_1_1___model_stub.html", null ],
      [ "stream", "classgpu__range__coder_1_1stream.html", "classgpu__range__coder_1_1stream" ],
      [ "gpu", "classgpu__range__coder_1_1gpu.html", "classgpu__range__coder_1_1gpu" ]
    ] ],
    [ "hydra_model", "namespacehydra__model.html", [
      [ "_RMSNorm", "classhydra__model_1_1___r_m_s_norm.html", null ],
      [ "_SwiGLU", "classhydra__model_1_1___swi_g_l_u.html", null ],
      [ "_HydraMambaBlock", "classhydra__model_1_1___hydra_mamba_block.html", null ],
      [ "HydraBOA", "classhydra__model_1_1_hydra_b_o_a.html", "classhydra__model_1_1_hydra_b_o_a" ]
    ] ],
    [ "model", null, [
      [ "_FeedForward", "classmodel_1_1___feed_forward.html", null ],
      [ "LSTMBlock", "classmodel_1_1_l_s_t_m_block.html", null ],
      [ "GRUBlock", "classmodel_1_1_g_r_u_block.html", null ],
      [ "_MinGRUCell", "classmodel_1_1___min_g_r_u_cell.html", "classmodel_1_1___min_g_r_u_cell" ],
      [ "MinGRUBlock", "classmodel_1_1_min_g_r_u_block.html", null ],
      [ "_RMSNorm", "classmodel_1_1___r_m_s_norm.html", null ],
      [ "_SwiGLU", "classmodel_1_1___swi_g_l_u.html", null ],
      [ "TransformerBlock", "classmodel_1_1_transformer_block.html", "classmodel_1_1_transformer_block" ],
      [ "_RWKV6TimeMix", "classmodel_1_1___r_w_k_v6_time_mix.html", "classmodel_1_1___r_w_k_v6_time_mix" ],
      [ "RWKV6Block", "classmodel_1_1_r_w_k_v6_block.html", null ],
      [ "_RWKV7TimeMix", "classmodel_1_1___r_w_k_v7_time_mix.html", "classmodel_1_1___r_w_k_v7_time_mix" ],
      [ "RWKV7Block", "classmodel_1_1_r_w_k_v7_block.html", null ],
      [ "_ROSA", "classmodel_1_1___r_o_s_a.html", "classmodel_1_1___r_o_s_a" ],
      [ "_RWKV8ROSA", "classmodel_1_1___r_w_k_v8_r_o_s_a.html", "classmodel_1_1___r_w_k_v8_r_o_s_a" ],
      [ "RWKV8Block", "classmodel_1_1_r_w_k_v8_block.html", "classmodel_1_1_r_w_k_v8_block" ],
      [ "_RGLRU", "classmodel_1_1___r_g_l_r_u.html", "classmodel_1_1___r_g_l_r_u" ],
      [ "GriffinBlock", "classmodel_1_1_griffin_block.html", null ],
      [ "_mLSTMCell", "classmodel_1_1__m_l_s_t_m_cell.html", "classmodel_1_1__m_l_s_t_m_cell" ],
      [ "xLSTMBlock", "classmodel_1_1x_l_s_t_m_block.html", null ],
      [ "ByteDataloader", "classmodel_1_1_byte_dataloader.html", "classmodel_1_1_byte_dataloader" ]
    ] ],
    [ "online_adapt", "namespaceonline__adapt.html", [
      [ "HeadAdapter", "classonline__adapt_1_1_head_adapter.html", "classonline__adapt_1_1_head_adapter" ]
    ] ],
    [ "Boa2Container", "struct_boa2_container.html", null ],
    [ "BoaBlockGPU", "struct_boa_block_g_p_u.html", null ],
    [ "BoaPredictorGPU", "struct_boa_predictor_g_p_u.html", null ],
    [ "CPPJoulesException", "class_c_p_p_joules_exception.html", null ],
    [ "EnergyState", "class_energy_state.html", "class_energy_state" ],
    [ "EnergyTracker", "class_energy_tracker.html", "class_energy_tracker" ],
    [ "FeedForwardGPU", "struct_feed_forward_g_p_u.html", null ],
    [ "GRUBlockGPU", "struct_g_r_u_block_g_p_u.html", null ],
    [ "HydraBoaGPU", "struct_hydra_boa_g_p_u.html", null ],
    [ "HydraHeadGPU", "struct_hydra_head_g_p_u.html", null ],
    [ "LayerNormGPU", "struct_layer_norm_g_p_u.html", null ],
    [ "LSTMBlockGPU", "struct_l_s_t_m_block_g_p_u.html", null ],
    [ "MambaBlockGPU", "struct_mamba_block_g_p_u.html", null ],
    [ "MambaConfig", "struct_mamba_config.html", null ],
    [ "MinGRUBlockGPU", "struct_min_g_r_u_block_g_p_u.html", null ],
    [ "nvmlAccountingStats_st", "structnvml_accounting_stats__st.html", "structnvml_accounting_stats__st" ],
    [ "nvmlBAR1Memory_st", "structnvml_b_a_r1_memory__st.html", "structnvml_b_a_r1_memory__st" ],
    [ "nvmlBridgeChipHierarchy_st", "structnvml_bridge_chip_hierarchy__st.html", "structnvml_bridge_chip_hierarchy__st" ],
    [ "nvmlBridgeChipInfo_st", "structnvml_bridge_chip_info__st.html", "structnvml_bridge_chip_info__st" ],
    [ "nvmlC2cModeInfo_v1_t", "structnvml_c2c_mode_info__v1__t.html", null ],
    [ "nvmlClkMonFaultInfo_struct", "structnvml_clk_mon_fault_info__struct.html", "structnvml_clk_mon_fault_info__struct" ],
    [ "nvmlClkMonStatus_status", "structnvml_clk_mon_status__status.html", "structnvml_clk_mon_status__status" ],
    [ "nvmlComputeInstanceInfo_st", "structnvml_compute_instance_info__st.html", "structnvml_compute_instance_info__st" ],
    [ "nvmlComputeInstancePlacement_st", "structnvml_compute_instance_placement__st.html", "structnvml_compute_instance_placement__st" ],
    [ "nvmlComputeInstanceProfileInfo_st", "structnvml_compute_instance_profile_info__st.html", "structnvml_compute_instance_profile_info__st" ],
    [ "nvmlComputeInstanceProfileInfo_v2_st", "structnvml_compute_instance_profile_info__v2__st.html", "structnvml_compute_instance_profile_info__v2__st" ],
    [ "nvmlComputeInstanceProfileInfo_v3_st", "structnvml_compute_instance_profile_info__v3__st.html", "structnvml_compute_instance_profile_info__v3__st" ],
    [ "nvmlConfComputeGpuAttestationReport_st", "structnvml_conf_compute_gpu_attestation_report__st.html", null ],
    [ "nvmlConfComputeGpuCertificate_st", "structnvml_conf_compute_gpu_certificate__st.html", null ],
    [ "nvmlConfComputeMemSizeInfo_st", "structnvml_conf_compute_mem_size_info__st.html", null ],
    [ "nvmlConfComputeSystemCaps_st", "structnvml_conf_compute_system_caps__st.html", null ],
    [ "nvmlConfComputeSystemState_st", "structnvml_conf_compute_system_state__st.html", null ],
    [ "NVMLDevice", "class_n_v_m_l_device.html", "class_n_v_m_l_device" ],
    [ "nvmlDeviceAttributes_st", "structnvml_device_attributes__st.html", "structnvml_device_attributes__st" ],
    [ "nvmlEccErrorCounts_st", "structnvml_ecc_error_counts__st.html", "structnvml_ecc_error_counts__st" ],
    [ "nvmlEncoderSessionInfo_st", "structnvml_encoder_session_info__st.html", "structnvml_encoder_session_info__st" ],
    [ "nvmlEventData_st", "structnvml_event_data__st.html", "structnvml_event_data__st" ],
    [ "nvmlExcludedDeviceInfo_st", "structnvml_excluded_device_info__st.html", "structnvml_excluded_device_info__st" ],
    [ "nvmlFBCSessionInfo_st", "structnvml_f_b_c_session_info__st.html", "structnvml_f_b_c_session_info__st" ],
    [ "nvmlFBCStats_st", "structnvml_f_b_c_stats__st.html", "structnvml_f_b_c_stats__st" ],
    [ "nvmlFieldValue_st", "structnvml_field_value__st.html", "structnvml_field_value__st" ],
    [ "nvmlGpmMetric_t", "structnvml_gpm_metric__t.html", "structnvml_gpm_metric__t" ],
    [ "nvmlGpmMetricsGet_t", "structnvml_gpm_metrics_get__t.html", "structnvml_gpm_metrics_get__t" ],
    [ "nvmlGpmSupport_t", "structnvml_gpm_support__t.html", "structnvml_gpm_support__t" ],
    [ "nvmlGpuDynamicPstatesInfo_st", "structnvml_gpu_dynamic_pstates_info__st.html", "structnvml_gpu_dynamic_pstates_info__st" ],
    [ "nvmlGpuFabricInfo_t", "structnvml_gpu_fabric_info__t.html", "structnvml_gpu_fabric_info__t" ],
    [ "nvmlGpuInstanceInfo_st", "structnvml_gpu_instance_info__st.html", "structnvml_gpu_instance_info__st" ],
    [ "nvmlGpuInstancePlacement_st", "structnvml_gpu_instance_placement__st.html", "structnvml_gpu_instance_placement__st" ],
    [ "nvmlGpuInstanceProfileInfo_st", "structnvml_gpu_instance_profile_info__st.html", "structnvml_gpu_instance_profile_info__st" ],
    [ "nvmlGpuInstanceProfileInfo_v2_st", "structnvml_gpu_instance_profile_info__v2__st.html", "structnvml_gpu_instance_profile_info__v2__st" ],
    [ "nvmlGpuInstanceProfileInfo_v3_st", "structnvml_gpu_instance_profile_info__v3__st.html", "structnvml_gpu_instance_profile_info__v3__st" ],
    [ "nvmlGpuThermalSettings_t", "structnvml_gpu_thermal_settings__t.html", null ],
    [ "nvmlGridLicensableFeature_st", "structnvml_grid_licensable_feature__st.html", "structnvml_grid_licensable_feature__st" ],
    [ "nvmlGridLicensableFeatures_st", "structnvml_grid_licensable_features__st.html", "structnvml_grid_licensable_features__st" ],
    [ "nvmlGridLicenseExpiry_st", "structnvml_grid_license_expiry__st.html", "structnvml_grid_license_expiry__st" ],
    [ "nvmlHwbcEntry_st", "structnvml_hwbc_entry__st.html", null ],
    [ "nvmlLedState_st", "structnvml_led_state__st.html", "structnvml_led_state__st" ],
    [ "nvmlMemory_st", "structnvml_memory__st.html", "structnvml_memory__st" ],
    [ "nvmlMemory_v2_st", "structnvml_memory__v2__st.html", "structnvml_memory__v2__st" ],
    [ "nvmlNvLinkPowerThres_st", "structnvml_nv_link_power_thres__st.html", "structnvml_nv_link_power_thres__st" ],
    [ "nvmlNvLinkUtilizationControl_st", "structnvml_nv_link_utilization_control__st.html", null ],
    [ "nvmlPciInfo_st", "structnvml_pci_info__st.html", "structnvml_pci_info__st" ],
    [ "nvmlPowerValue_v2_t", "structnvml_power_value__v2__t.html", "structnvml_power_value__v2__t" ],
    [ "nvmlProcessDetail_v1_t", "structnvml_process_detail__v1__t.html", "structnvml_process_detail__v1__t" ],
    [ "nvmlProcessDetailList_v1_t", "structnvml_process_detail_list__v1__t.html", "structnvml_process_detail_list__v1__t" ],
    [ "nvmlProcessInfo_v1_st", "structnvml_process_info__v1__st.html", "structnvml_process_info__v1__st" ],
    [ "nvmlProcessInfo_v2_st", "structnvml_process_info__v2__st.html", "structnvml_process_info__v2__st" ],
    [ "nvmlProcessUtilizationSample_st", "structnvml_process_utilization_sample__st.html", "structnvml_process_utilization_sample__st" ],
    [ "nvmlPSUInfo_st", "structnvml_p_s_u_info__st.html", "structnvml_p_s_u_info__st" ],
    [ "nvmlRowRemapperHistogramValues_st", "structnvml_row_remapper_histogram_values__st.html", null ],
    [ "nvmlSample_st", "structnvml_sample__st.html", "structnvml_sample__st" ],
    [ "nvmlUnitFanInfo_st", "structnvml_unit_fan_info__st.html", "structnvml_unit_fan_info__st" ],
    [ "nvmlUnitFanSpeeds_st", "structnvml_unit_fan_speeds__st.html", "structnvml_unit_fan_speeds__st" ],
    [ "nvmlUnitInfo_st", "structnvml_unit_info__st.html", "structnvml_unit_info__st" ],
    [ "nvmlUtilization_st", "structnvml_utilization__st.html", "structnvml_utilization__st" ],
    [ "nvmlValue_st", "unionnvml_value__st.html", "unionnvml_value__st" ],
    [ "nvmlVgpuInstanceUtilizationSample_st", "structnvml_vgpu_instance_utilization_sample__st.html", "structnvml_vgpu_instance_utilization_sample__st" ],
    [ "nvmlVgpuLicenseExpiry_st", "structnvml_vgpu_license_expiry__st.html", "structnvml_vgpu_license_expiry__st" ],
    [ "nvmlVgpuLicenseInfo_st", "structnvml_vgpu_license_info__st.html", "structnvml_vgpu_license_info__st" ],
    [ "nvmlVgpuMetadata_st", "structnvml_vgpu_metadata__st.html", "structnvml_vgpu_metadata__st" ],
    [ "nvmlVgpuPgpuCompatibility_st", "structnvml_vgpu_pgpu_compatibility__st.html", "structnvml_vgpu_pgpu_compatibility__st" ],
    [ "nvmlVgpuPgpuMetadata_st", "structnvml_vgpu_pgpu_metadata__st.html", "structnvml_vgpu_pgpu_metadata__st" ],
    [ "nvmlVgpuProcessUtilizationSample_st", "structnvml_vgpu_process_utilization_sample__st.html", "structnvml_vgpu_process_utilization_sample__st" ],
    [ "nvmlVgpuSchedulerCapabilities_st", "structnvml_vgpu_scheduler_capabilities__st.html", "structnvml_vgpu_scheduler_capabilities__st" ],
    [ "nvmlVgpuSchedulerGetState_st", "structnvml_vgpu_scheduler_get_state__st.html", "structnvml_vgpu_scheduler_get_state__st" ],
    [ "nvmlVgpuSchedulerLog_st", "structnvml_vgpu_scheduler_log__st.html", "structnvml_vgpu_scheduler_log__st" ],
    [ "nvmlVgpuSchedulerLogEntries_st", "structnvml_vgpu_scheduler_log_entries__st.html", "structnvml_vgpu_scheduler_log_entries__st" ],
    [ "nvmlVgpuSchedulerParams_t", "unionnvml_vgpu_scheduler_params__t.html", "unionnvml_vgpu_scheduler_params__t" ],
    [ "nvmlVgpuSchedulerSetParams_t", "unionnvml_vgpu_scheduler_set_params__t.html", "unionnvml_vgpu_scheduler_set_params__t" ],
    [ "nvmlVgpuSchedulerSetState_st", "structnvml_vgpu_scheduler_set_state__st.html", "structnvml_vgpu_scheduler_set_state__st" ],
    [ "nvmlVgpuVersion_st", "structnvml_vgpu_version__st.html", "structnvml_vgpu_version__st" ],
    [ "nvmlViolationTime_st", "structnvml_violation_time__st.html", "structnvml_violation_time__st" ],
    [ "RAPLDevice", "class_r_a_p_l_device.html", "class_r_a_p_l_device" ],
    [ "RCDecState", "struct_r_c_dec_state.html", null ],
    [ "RCState", "struct_r_c_state.html", null ]
];