var topics =
[
    [ "Device Structs", "group__nvml_device_structs.html", "group__nvml_device_structs" ],
    [ "Device Enums", "group__nvml_device_enumvs.html", "group__nvml_device_enumvs" ],
    [ "Field Value Enums", "group__nvml_field_value_enums.html", "group__nvml_field_value_enums" ],
    [ "Unit Structs", "group__nvml_unit_structs.html", "group__nvml_unit_structs" ],
    [ "Accounting Statistics", "group__nvml_accounting_stats.html", "group__nvml_accounting_stats" ],
    [ "Encoder Structs", "group__nvml_encoder_structs.html", "group__nvml_encoder_structs" ],
    [ "Frame Buffer Capture Structures", "group__nvml_f_b_c_structs.html", "group__nvml_f_b_c_structs" ],
    [ "definitions related to the drain state", "group__nvml_drain_defs.html", "group__nvml_drain_defs" ],
    [ "/nvmlDevice definitions related to Confidential Computing", "group__nvml_system.html", "group__nvml_system" ],
    [ "Initialization and Cleanup", "group__nvml_initialization_and_cleanup.html", "group__nvml_initialization_and_cleanup" ],
    [ "Error reporting", "group__nvml_error_reporting.html", "group__nvml_error_reporting" ],
    [ "Constants", "group__nvml_constants.html", "group__nvml_constants" ],
    [ "System Queries", "group__nvml_system_queries.html", "group__nvml_system_queries" ],
    [ "Unit Queries", "group__nvml_unit_queries.html", "group__nvml_unit_queries" ],
    [ "Device Queries", "group__nvml_device_queries.html", "group__nvml_device_queries" ],
    [ "Unit Commands", "group__nvml_unit_commands.html", "group__nvml_unit_commands" ],
    [ "Device Commands", "group__nvml_device_commands.html", "group__nvml_device_commands" ],
    [ "NvLink Methods", "group___nv_link.html", "group___nv_link" ],
    [ "Event Handling Methods", "group__nvml_events.html", "group__nvml_events" ],
    [ "Drain states", "group__nvml_z_p_i.html", "group__nvml_z_p_i" ],
    [ "Field Value Queries", "group__nvml_field_value_queries.html", "group__nvml_field_value_queries" ],
    [ "Enums, Constants and Structs", "group__v_g_p_u.html", null ],
    [ "vGPU APIs", "group__nvml_virtual_gpu_queries.html", "group__nvml_virtual_gpu_queries" ],
    [ "vGPU Management", "group__nvml_vgpu.html", "group__nvml_vgpu" ],
    [ "vGPU Migration", "group__nvml.html", "group__nvml" ],
    [ "vGPU Utilization and Accounting", "group__nvml_util.html", "group__nvml_util" ],
    [ "Excluded GPU Queries", "group__nvml_excluded_gpu_queries.html", "group__nvml_excluded_gpu_queries" ],
    [ "Multi Instance GPU Management", "group__nvml_multi_instance_g_p_u.html", "group__nvml_multi_instance_g_p_u" ],
    [ "NVML GPM", "group___g_p_m.html", "group___g_p_m" ],
    [ "VirtualGPU", "group__virtual_g_p_u.html", "group__virtual_g_p_u" ],
    [ "NvmlClocksEventReasons", "group__nvml_clocks_event_reasons.html", "group__nvml_clocks_event_reasons" ]
];